Map/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.conf import settings
from django.contrib import admin
import os
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'HealthMap.views.HomePage'),
    (r'^lookup/$', 'HealthMap.views.LookupRequest'),
    (r'^random/$', 'HealthMap.views.RandomRequest'),
    url(r'^dataset_lookup/$','HealthMap.views.dataset_lookup', name='dataset_lookup'),
    url(r'^dataset_gis/$','HealthMap.views.dataset_gis', name='dataset_gis'),
    url(r'^history/$', 'HealthMap.views.showHistory', name='showHistory'),

    url(r'^admin/', include(admin.site.urls)),
)

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
    )

HealthMap/models.py
from django.db import models
import datetime

class Region(models.Model):
    state = models.CharField(max_length=2, verbose_name='state', db_index=True)
    stateName = models.CharField(max_length=50, verbose_name='state name')
    county = models.CharField(max_length=50, blank=True, db_index=True)
    fips = models.CharField(max_length=5, blank=True)
    imageURL = models.URLField(blank=True)
    def __unicode__(self):
        return u'state:%s (county:%s)' % (self.state, self.county)
    class Meta:
        ordering = ['state', 'county']
    
class Polyline(models.Model):
    region = models.ForeignKey('Region', db_index=True)
    lat = models.DecimalField(max_digits=7, decimal_places=4, verbose_name='latitude')
    lng = models.DecimalField(max_digits=7, decimal_places=4, verbose_name='longitude')
    def __unicode__(self):
        return u'lat:%3.4f lng:%3.4f' % (self.lat, self.lng)
    class Meta:
        ordering = ['pk']

class Category(models.Model):
    name = models.CharField(max_length=25)
    imageURL = models.URLField(blank=True)
    def __unicode__(self):
        return self.name

class Dataset(models.Model):
    category = models.ForeignKey('Category')
    name = models.CharField(max_length=80, db_index=True)
    legend = models.CharField(max_length=25, blank=True)
    description = models.TextField(blank=True)
    imageURL = models.URLField(blank=True)
    citations = models.TextField(blank=True)
    maplatitude = models.CharField(max_length=15, blank=True)
    maplongitude = models.CharField(max_length=15, blank=True)
    mapzoom = models.CharField(max_length=2, blank=True)
    created = models.DateField(editable=False)
    updated = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not 'force_insert' in kwargs:
            kwargs['force_insert'] = False
        if not 'force_update' in kwargs:
            kwargs['force_update'] = False
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()
        super(Dataset, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Range(models.Model):
    dataset = models.ForeignKey('Dataset')
    low = models.DecimalField(max_digits=12, decimal_places=3)
    high = models.DecimalField(max_digits=12, decimal_places=3)
    name = models.CharField(max_length=15)
    color = models.CharField(max_length=7)   # eg. #AAA000
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['low']

class Datarow(models.Model):
    dataset = models.ForeignKey('Dataset', db_index=True)
    region = models.ForeignKey('Region', db_index=True)
    value = models.DecimalField(max_digits=12, decimal_places=3)
    def color(self):
        return_color = "#FFFFF0"    # default color is 'Ivory'
        for range in self.dataset.range_set.all():
            if self.value>range.low and self.value<range.high:
                return_color = range.color
                break
        return unicode(return_color)
    def __unicode__(self):
        return unicode(self.value)
    class Meta:
        unique_together = ("dataset", "region")

class History(models.Model):
    name = models.CharField(max_length=80)
    searched = models.DateTimeField(editable=False)
    latitude = models.CharField(max_length=15, blank=True)
    longitude = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=80, blank=True)
    def save(self, *args, **kwargs):
        if not 'force_insert' in kwargs:
            kwargs['force_insert'] = False
        if not 'force_update' in kwargs:
            kwargs['force_update'] = False
        self.searched = datetime.datetime.today()
        super(History, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name
    

HealthMap/forms.py
from django import forms

class LookupForm(forms.Form):
    autocomplete                   = forms.CharField()
    latitude                            = forms.CharField(required = False)
    longitude                          = forms.CharField(required = False)

Map/templates/autocomplete.html
	<style>
	.ui-autocomplete {
		max-height: 235px;
		overflow-y: auto;
		overflow-x: hidden;
		padding-right: 20px;
	}
	</style>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <script>
  $(document).ready(function() {
    $("input#id_autocomplete").autocomplete({
    source: "/dataset_lookup/",
    minLength: 2, });
     });
  </script>

Map/templates/base.html
<!--[if IE]>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<![endif]-->
<html>
<head>
<title>Health Map</title>
    <link rel='stylesheet' type='text/css' href='/static/css/HealthMap.css' />
    {% block extrahead %}{% endblock %}
</head>
<body>
<div id='pageContainer'>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

Map/templates/history.html
{% extends 'base.html' %}
{% block extrahead %}
{% include "autocomplete.html" %}
{% endblock %}
	
{% block content %}
<h1>
<a href= "/" >Health Map </a>searches:<br>
</h1>

<div id='history'>
{% for map in history %}
   <small>{{ map.searched }}</small> &nbsp;&nbsp;<a href="/?id={{ map.id }}"/>{{ map.name }}</a>
   {% if map.location != None and map.location|length > 1 %}
   <small><font color="gray">&nbsp; (searched from: {{ map.location }})</font></small>
   {% endif %}
   <br>
{% endfor %}
</div>

<div id='datasetInfo'>
<br>
<img src="/static/images/history_icon.png" id="history" alt="search history" height="35" width="35" /> 
<a href="http://www.facebook.com/USHealthMap" target="_blank"><img src="/static/images/fb_icon.png" height="35" width="35" /></a>
<a href= "mailto:info@healthmap.us" ><img src="/static/images/email_icon.png" id="email" alt="Email us" height="35" width="35" /></a>
 <br>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=7390162215";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
</div>

<div id="footer">
<small> <a href= "mailto:info@healthmap.us" >HealthMap.us (2012)</a></small>
</div>
{% endblock %}

Map/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
 
	<style type="text/css">
 
		html,
		body {
			height: 100% ;
			margin: 0px 0px 0px 0px ;
			overflow: hidden ;
			padding: 0px 0px 0px 0px ;
			width: 100% ;
			}
 
		#mapContainer {
			height: 100% ;
			width: 100% ;
			}
 
	</style>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
</head>
<body>
 
 
	<div id="map">
	</div>
 
 
	<script type="text/javascript">
 
    $.loadmap();
    
 var loadMap = function(){
  var GM = google.maps, 
      defaultPosition = new GM.LatLng(42, -71),
      mapOptions = {
      zoom: 12, 
      center: defaultPosition, 
      mapTypeId: GM.MapTypeId.ROADMAP},
    map = new GM.Map( 
      document.getElementById('map'), 
      mapOptions
    ), 
    success = function( data ){
      var position = new GM.LatLng( 
        data.coords.latitude, 
        data.coords.longitude 
      ), 
         niceAddress = 'Your location',
         geocoder = new GM.Geocoder();
      geocoder.geocode({ 
        'latLng': position },
         function( results, status ) {
           if ( status == GM.GeocoderStatus.OK ){
             if (results[0]) {
               niceAddress = results[0].formatted_address; 
             }
           }
           var infowindow = new GM.InfoWindow({
             map: map, 
             position: position, 
             content: niceAddress
           });
         }
       );
      map.setCenter( position );
    }, 
    failure = function( error ){ 
      var formResponse = function(){ 
        var geocoder = new GM.Geocoder(),
            position = defaultPosition, 
            niceAddress = 'Sorry We Couldn't Find Your Location';
        geocoder.geocode({
     'address':document.getElementById('location').value 
    }, 
          function( results, status ) {
            if ( status == GM.GeocoderStatus.OK ){ 
              if (results[0]) {
                niceAddress = results[0].formatted_address; 
                position = new GM.LatLng(
                  results[0].geometry.location.lat(),
                  results[0].geometry.location.lng() 
                )
               } 
             }
             var options = {
                map: map, 
                position: position, 
                content: niceAddress
              },
              infowindow = new google.maps.InfoWindow(options);
              map.setCenter(options.position);
              document.getElementById('geocode').style.display='none';
           }
         )
       return false; 
     } 
     var fallback = document.createElement('form');
     fallback.id='geocode';
      if ( error ) {

       switch(error.code) {

         case error.PERMISSION_DENIED:

     	    fallback.innerHTML += "<p>You chose not share geolocation data. Please, use the form below. </p>" ;  

         break;  

	 case error.POSITION_UNAVAILABLE:

            fallback.innerHTML += "<p>Sorry, we couldn't determine your location. Please, use the form below. </p>" ;

         break;  

         case error.TIMEOUT: 

            fallback.innerHTML += "<p>Sorry, the location request time out. Please, use the form below. </p>" ;

         break;  

         default: 

            fallback.innerHTML += "<p>Sorry, there was an error. Please use the form below. </p>" ;

         break;

       }  	

    }

    fallback.innerHTML += "<label for='location'>Eneter Your Location <input type='text' id='location' /></label><input type='submit' />";

    fallback.onsubmit = formResponse;

    document.getElementById("main").appendChild( fallback );

  };

  if (navigator.geolocation){
    navigator.geolocation.getCurrentPosition( success, failure, {timeout:5000} ) ;			
  } else {
    failure();	
  } 	
}
 
	</script>
 
</body>
</html>

Map/templates/index.html
{% extends 'base.html' %}
{% block extrahead %}
{% include "autocomplete.html" %}
{% endblock %}
	
{% block content %}

<table><tr><td>
<form action="/lookup/" method="post">
{% csrf_token %}
	<label for="tags">Search: </label>{{ form.autocomplete }}<input type="submit" style="height: 32px; width: 55px" value="Map" alt="Map"/>
{{form.latitude.as_hidden }}
{{form.longitude.as_hidden }}
</form></td><td>
<form action="/random/" method="post">
{% csrf_token %}
	<input type="submit" style="height: 32px; width: 75px" value="Random" alt="Map"/>
</form></td></td>
<div id='wait'>
<img src="/static/images/wait_spiral.gif" id="wait" height="40" /> <br>
</div></td>
</tr>
</table>


 <div id="map" style="height: 600px">


    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=AIzaSyCBo3eZFzgJ_u2Wz7ZOVeHz24wjgpmsMGE" type="text/javascript">
        
    </script>
  <body onunload="GUnload()">

    <noscript><b>JavaScript must be enabled in order for you to use Google Maps.</b> 
      However, it seems JavaScript is either disabled or not supported by your browser. 
      To view Google Maps, enable JavaScript by changing your browser options, and then 
      try again.
    </noscript>
 

    <script type="text/javascript">
    //<![CDATA[

    if (GBrowserIsCompatible()) {
      var polys = [];
      var labels = [];
      GPolygon.prototype.Contains = function(point) {
        var j=0;
        var oddNodes = false;
        var x = point.lng();
        var y = point.lat();
        for (var i=0; i < this.getVertexCount(); i++) {
          j++;
          if (j == this.getVertexCount()) {j = 0;}
          if (((this.getVertex(i).lat() < y) && (this.getVertex(j).lat() >= y))
          || ((this.getVertex(j).lat() < y) && (this.getVertex(i).lat() >= y))) {
            if ( this.getVertex(i).lng() + (y - this.getVertex(i).lat())
            /  (this.getVertex(j).lat()-this.getVertex(i).lat())
            *  (this.getVertex(j).lng() - this.getVertex(i).lng())<x ) {
              oddNodes = !oddNodes
            }
          }
        }
        return oddNodes;
      }

      // Display the map, with some controls and set the initial location 
      var map = new GMap2(document.getElementById("map"));
      map.addControl(new GLargeMapControl());
      map.addControl(new GMapTypeControl());
      {% if dataset.mapzoom != None and dataset.mapzoom|length > 0 %}
          map.setCenter(new GLatLng({{ dataset.maplatitude }}, {{ dataset.maplongitude }}), {{ dataset.mapzoom }});
      {% else %}
          map.setCenter(new GLatLng(33.1,-95),4);
      {% endif %}



$(document).ready(function () {
    // wire up button click
        // test for presence of geolocation
        if (navigator && navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(geo_success, geo_error);
        } else {
            error('Geolocation is not supported.');
        }
});

function geo_success(position) {
	 var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
     var point = new GLatLng(position.coords.latitude, position.coords.longitude);
     map.addOverlay(new GMarker(point));

     printLatLong(String(position.coords.latitude), String(position.coords.longitude));
    // place geo-coordinates in form hidden fields
    document.getElementById('id_latitude').value = String(position.coords.latitude);
    document.getElementById('id_longitude').value = String(position.coords.longitude);
}

function geo_error(err) {
    if (err.code == 1) {
        console.log('The user denied the request for location information.')
    } else if (err.code == 2) {
        console.log('Your location information is unavailable.')
    } else if (err.code == 3) {
        console.log('The request to get your location timed out.')
    } else {
        console.log('An unknown error occurred while requesting your location.')
    }
}

function printLatLong(lat, long) {
    var theDiv = document.getElementById('footer');
    var content = document.createTextNode('  (Your coordinates: Lat: ' + lat.substring(0,8) + ' Long: ' + long.substring(0,8) + ')');
    theDiv.appendChild(content);
}

function error(msg) {
    alert(msg);
}


      GEvent.addListener(map, "click", function(overlay,point) {
        if (!overlay) {
          for (var i=0; i<polys.length; i++) {
            if (polys[i].Contains(point)) {
              map.openInfoWindowHtml(point,""+labels[i]);
              //i = 999; // Jump out of loop
            }
          }
        }
      });

      // defaults
      var line_color = "#AAA000";
      var opaque = 0.75;
      
      // working vars
      var color = "";
      var pts = [];
      var i = 0;

      $.getJSON('dataset_gis/?id={{ dataset.id }}', 
      function(data) {
          for (var row=0; row<data.length; row++)    {
              pts = [];
              for (var line=0; line<data[row].points.length; line++)
                {   pts[line] = new GLatLng(parseFloat(data[row].points[line].lat), parseFloat(data[row].points[line].lng));   } 
              var poly = new GPolygon(pts, line_color, 1,1, data[row].color, opaque, {clickable:false});
              polys.push(poly);
              labels.push(data[row].state + '  ' + data[row].county + ' (' + data[row].value + ')');
              map.addOverlay(poly);
          };
      document.getElementById('wait').style.visibility = 'hidden'; 

      });    
    }
    
    // display a warning if the browser was not compatible
    else {
      alert("Sorry, the Google Maps API is not compatible with this browser");
    }

    </script>

  </div>

<div id='datasetInfo'>
{%  if dataset.name != "Empty" %}
    <font color="blue"><b>{{ dataset.name }} </b></font> <br>
    {{ dataset.description }} <br>
    {% if dataset.citations|length > 0 %}
    <small>(source:{{ dataset.citations }}) </small><br>
    {% endif %}
    {% if dataset.imageURL|length > 0 %}
        <img src="{{ dataset.imageURL }}" alt="Dataset image" height="100" /> 
    {% endif %}
    <br>
    <table>
    {% for range in dataset_range %}
    <tr><td><font size=2>
     <span style="background-color:{{ range.color }}">&nbsp;&nbsp;&nbsp;&nbsp; </span> &nbsp;
        {{ range.name }}</td><tr><td><font size=2>
        {{ range.low|floatformat:1 }} - {{ range.high|floatformat:1 }}
    </font></td></tr>
    {% endfor %}
    </table>
{% else %}
    <font color="blue"> <small>Enter search words <br>or click 'Random' to get map </small></font> <br>
{% endif %}

<br>
<a href="/history"><img src="/static/images/history_icon.png" id="history" alt="search history" height="35" width="35" /></a>
<a href="http://www.facebook.com/USHealthMap" target="_blank"><img src="/static/images/fb_icon.png" height="35" width="35" /></a>
<a href= "mailto:info@healthmap.us" ><img src="/static/images/email_icon.png" id="email" alt="Email us" height="35" width="35" /></a>
<br>
<img src="/static/images/Logo.jpg" height="25"/>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

 <div class="fb-like" data-href="http://www.facebook.com/USHealthMap" data-send="true" data-layout="box_count" data-width="450" data-show-faces="true"></div>

</div>

<div id="footer">
<a href= "mailto:info@healthmap.us" >HealthMap.us (2012)</a>

</div>
{% endblock %}

Map/templates/index_.html
{% extends 'base.html' %}
{% block extrahead %}
{% include "autocomplete.html" %}
{% endblock %}
	
{% block content %}

<form action="/lookup/" method="post">
{% csrf_token %}
	<label for="tags">Tags: </label>{{ form.autocomplete }}<input type="submit" value="Map" alt="Map"/>
</form>

<div id='datasetInfo'>
{%  if dataset.name != "Empty" %}
    Map: <b>{{ dataset.name }} </b> <br>
    {{ dataset.description }} <br>
    {% if dataset.imageURL|length > 0 %}
        <img src="{{ dataset.imageURL }}" alt="Dataset image" height="100" width="100" /> 
    {% endif %}
    <br>
    <table>

    {% for range in dataset_range %}
    <tr><td><font size=2>
     <span style="background-color:{{ range.color }}">&nbsp;&nbsp;&nbsp;&nbsp; </span> &nbsp;
        {{ range.name }}</td><tr><td><font size=2>
        {{ range.low|floatformat:1 }} - {{ range.high|floatformat:1 }}
    </font></td></tr>
    {% endfor %}
    </table>
{% endif %}
</div>


<script type='text/javascript'>
$(document).ready(function(){
    $.getJSON('dataset_gis/?id=16', 
        function(data) {
            alert(data.length);
            for (row in data)
            {
                document.write(data[row].state + "<br />");
                for (line in data[row].points)
                {
                    document.write(data[row].points[line].lat + " - ");
                }
            }
    });
 });
    
</script>


    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=AIzaSyCBo3eZFzgJ_u2Wz7ZOVeHz24wjgpmsMGE" type="text/javascript"></script>
  <body onunload="GUnload()">

    <div id="map" style="width: 750px; height: 600px"></div>

    <noscript><b>JavaScript must be enabled in order for you to use Google Maps.</b> 
      However, it seems JavaScript is either disabled or not supported by your browser. 
      To view Google Maps, enable JavaScript by changing your browser options, and then 
      try again.
    </noscript>
 

    <script type="text/javascript">
    //<![CDATA[

    if (GBrowserIsCompatible()) {
      var polys = [];
      var labels = [];
      GPolygon.prototype.Contains = function(point) {
        var j=0;
        var oddNodes = false;
        var x = point.lng();
        var y = point.lat();
        for (var i=0; i < this.getVertexCount(); i++) {
          j++;
          if (j == this.getVertexCount()) {j = 0;}
          if (((this.getVertex(i).lat() < y) && (this.getVertex(j).lat() >= y))
          || ((this.getVertex(j).lat() < y) && (this.getVertex(i).lat() >= y))) {
            if ( this.getVertex(i).lng() + (y - this.getVertex(i).lat())
            /  (this.getVertex(j).lat()-this.getVertex(i).lat())
            *  (this.getVertex(j).lng() - this.getVertex(i).lng())<x ) {
              oddNodes = !oddNodes
            }
          }
        }
        return oddNodes;
      }

      // Display the map, with some controls and set the initial location 
      var map = new GMap2(document.getElementById("map"));
      map.addControl(new GLargeMapControl());
      map.addControl(new GMapTypeControl());
      map.setCenter(new GLatLng(33.1,-95),4);


      GEvent.addListener(map, "click", function(overlay,point) {
        if (!overlay) {
          for (var i=0; i<polys.length; i++) {
            if (polys[i].Contains(point)) {
              map.openInfoWindowHtml(point,"You clicked on "+labels[i]);
              //i = 999; // Jump out of loop
            }
          }
        }
      });

      // defaults
      var line_color = "#AAA000";
      var opaque = 0.75;
      
      // working vars
      var color = "";
      var pts = [];
      var i = 0;

{% for row in dataset.datarow_set.all %}
    {% if row.region.state != "OO" %}
            color = "#FFF000";
            pts = [];
            i = 0;
        
    // Polylines for a region
    {% for line in row.region.polyline_set.all %}
               pts[i++] = new GLatLng(parseFloat({{ line.lat }}), parseFloat({{ line.lng }}));
    {% endfor %}
    {%  if row.color == "#FFFFF0" %}
            // got back default color so let's use default range
            {% for range in dataset_range %}
                {% if row.value|rjust:11 >= range.low|rjust:11 and row.value|rjust:11 <= range.high|rjust:11 %}
                    var poly = new GPolygon(pts,line_color,1,1,"{{ range.color }}",opaque,{clickable:false});
                {% endif %}
            {% endfor %}
    {% else %}
            var poly = new GPolygon(pts,line_color,1,1,"{{ row.color }}",opaque,{clickable:false});
    {% endif %}
            polys.push(poly);
            labels.push("{{ row.region.state }}");
            map.addOverlay(poly);
    {% endif %}
{% endfor %}

//      request.send(null);

    }
    
    // display a warning if the browser was not compatible
    else {
      alert("Sorry, the Google Maps API is not compatible with this browser");
    }

    </script>
  </div>

{% endblock %}

Map/templates/script.html
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCBo3eZFzgJ_u2Wz7ZOVeHz24wjgpmsMGE&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            myOptions);
      }
    </script>